// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "FooC.h"
#include "tao/CDR.h"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_array/array_cs.cpp:89

Try::Foo::_values_slice *
Try::Foo::_values_dup (const Try::Foo::_values_slice *_tao_src_array)
{
  Try::Foo::_values_slice *_tao_dup_array = Try::Foo::_values_alloc ();
  
  if (_tao_dup_array)
    {
      Try::Foo::_values_copy (_tao_dup_array, _tao_src_array);
    }
  
  return _tao_dup_array;
}

Try::Foo::_values_slice *
Try::Foo::_values_alloc ()
{
  Try::Foo::_values_slice *retval {};
  ACE_NEW_RETURN (retval, ::CORBA::Long[5], nullptr);
  return retval;
}

void
Try::Foo::_values_free (Try::Foo::_values_slice *_tao_slice)
{
  delete [] _tao_slice;
}

void
Try::Foo::_values_copy (
    Try::Foo::_values_slice * _tao_to,
    const Try::Foo::_values_slice *_tao_from)
{
  // Copy each individual element.
  for (::CORBA::ULong i0 = 0; i0 < 5; ++i0)
    {
      _tao_to[i0] = _tao_from[i0];
    }
}


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_cs.cpp:104



#if !defined (_TRY_FOO__TAO_SEQ_CORBA_LONG__CS_)
#define _TRY_FOO__TAO_SEQ_CORBA_LONG__CS_

Try::Foo::_tao_seq_CORBA_Long_::_tao_seq_CORBA_Long_ (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence< ::CORBA::Long> (max)
{}

Try::Foo::_tao_seq_CORBA_Long_::_tao_seq_CORBA_Long_ (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::Long * buffer,
    ::CORBA::Boolean release)
  : ::TAO::unbounded_value_sequence< ::CORBA::Long>
    (max, length, buffer, release)
{}

#endif /* end #if !defined */
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/cdr_op_cs.cpp:29


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (TAO_OutputCDR &strm, Try::Color _tao_enumerator)
{
  return strm << static_cast< ::CORBA::ULong> (_tao_enumerator);
}

::CORBA::Boolean operator>> (TAO_InputCDR &strm, Try::Color & _tao_enumerator)
{
  ::CORBA::ULong _tao_temp = 0;
  ::CORBA::Boolean const _tao_success = strm >> _tao_temp;
  
  if (_tao_success)
    {
      _tao_enumerator = static_cast<Try::Color> (_tao_temp);
    }
  
  return _tao_success;
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_array/cdr_op_cs.cpp:162


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Try::Foo::_values_forany &_tao_array)
{
  return strm.write_long_array (
      reinterpret_cast <const ACE_CDR::Long *> (_tao_array.in ()),
      5);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Try::Foo::_values_forany &_tao_array)
{
  return strm.read_long_array (
      reinterpret_cast <ACE_CDR::Long *> (_tao_array.out ()),
      5);
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_cs.cpp:92

#if !defined _TAO_CDR_OP_Try_Foo__tao_seq_CORBA_Long__CPP_
#define _TAO_CDR_OP_Try_Foo__tao_seq_CORBA_Long__CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Try::Foo::_tao_seq_CORBA_Long_ &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Try::Foo::_tao_seq_CORBA_Long_ &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_Try_Foo__tao_seq_CORBA_Long__CPP_ */
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_cs.cpp:48


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Try::Foo &_tao_aggregate)
{
  Try::Foo::_values_forany _tao_aggregate_values
    (const_cast<Try::Foo::_values_slice*> (
      _tao_aggregate.values));
  return
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.bazz.in (), 256)) &&
    (strm << _tao_aggregate.temp) &&
    (strm << _tao_aggregate_values) &&
    (strm << _tao_aggregate.dynamic) &&
    (strm << _tao_aggregate.fav);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Try::Foo &_tao_aggregate)
{
  Try::Foo::_values_forany _tao_aggregate_values
    (const_cast<Try::Foo::_values_slice*> (
      _tao_aggregate.values));
  return
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.bazz.out (), 256)) &&
    (strm >> _tao_aggregate.temp) &&
    (strm >> _tao_aggregate_values) &&
    (strm >> _tao_aggregate.dynamic) &&
    (strm >> _tao_aggregate.fav);
}

TAO_END_VERSIONED_NAMESPACE_DECL



