// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_SRC_FOOC_KESBEF_H_
#define _TAO_IDL_SRC_FOOC_KESBEF_H_


#include /**/ <ace/config-all.h>

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include <tao/ORB.h>
#include <tao/Basic_Types_IDLv4.h>
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include <tao/String_Manager_T.h>
#include <tao/Sequence_T.h>
#include <tao/Seq_Var_T.h>
#include <tao/Seq_Out_T.h>
#include <tao/VarOut_T.h>
#include <tao/Array_VarOut_T.h>
#include <tao/Arg_Traits_T.h>
#include <tao/Basic_Arguments.h>
#include <tao/Special_Basic_Arguments.h>
#include <tao/Any_Insert_Policy_T.h>
#include <tao/Basic_Argument_T.h>
#include <tao/Fixed_Size_Argument_T.h>
#include <tao/Var_Size_Argument_T.h>
#include <tao/BD_String_Argument_T.h>
#include "tao/Fixed_Array_Argument_T.h"
#include "tao/Var_Array_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 4 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace Try
{
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/enum_ch.cpp:39

  enum Color
  {
    RED,
    GREEN,
    BLUE
  };

  typedef Color &Color_out;
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:258

  

  struct Foo;
  using Foo_var = ::TAO_Var_Var_T<Foo>;
  using Foo_out = ::TAO_Out_T<Foo>;

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/structure_ch.cpp:47

  

  struct  Foo
  {
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    
    using _var_type = Foo_var;
    using _out_type = Foo_out;
    
    ::TAO::String_Manager bazz;
    ::CORBA::Double temp;
    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_array/array_ch.cpp:47

    

    typedef ::CORBA::Long _values[5];
    typedef ::CORBA::Long _values_slice;
    struct _values_tag {};
    

    typedef
      TAO_Array_Forany_T<
          _values,
          _values_slice,
          _values_tag
        >
      _values_forany;

    static _values_slice *
    _values_alloc ();

    static void
    _values_free (
        _values_slice *_tao_slice);
    
    static _values_slice *
    _values_dup (
        const _values_slice *_tao_slice);
    
    static void
    _values_copy (
        _values_slice *_tao_to,
        const _values_slice *_tao_from);

    _values values;
    

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

    

#if !defined (_TRY_FOO__TAO_SEQ_CORBA_LONG__CH_)
#define _TRY_FOO__TAO_SEQ_CORBA_LONG__CH_

    

    class  _tao_seq_CORBA_Long_
      : public
          ::TAO::unbounded_value_sequence< ::CORBA::Long>
    {
    public:
      _tao_seq_CORBA_Long_ () = default;
      _tao_seq_CORBA_Long_ (::CORBA::ULong max);
      _tao_seq_CORBA_Long_ (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        ::CORBA::Long* buffer,
        ::CORBA::Boolean release = false);
      _tao_seq_CORBA_Long_ (const _tao_seq_CORBA_Long_ &) = default;
      _tao_seq_CORBA_Long_ (_tao_seq_CORBA_Long_ &&) = default;
      _tao_seq_CORBA_Long_& operator= (const _tao_seq_CORBA_Long_ &) = default;
      _tao_seq_CORBA_Long_& operator= (_tao_seq_CORBA_Long_ &&) = default;
      virtual ~_tao_seq_CORBA_Long_ () = default;
      
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_field/field_ch.cpp:338

    typedef _tao_seq_CORBA_Long_ _dynamic_seq;
    _tao_seq_CORBA_Long_ dynamic;
    Try::Color fav;
  };


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module Try
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:889

  

  template<>
  class Arg_Traits< ::Try::Color>
    : public
        Basic_Arg_Traits_T<
            ::Try::Color,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:931

  

  template<>
  class Arg_Traits< ::Try::Foo>
    : public
        Var_Size_Arg_Traits_T<
            ::Try::Foo,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_CORBA_STRING_256__ARG_TRAITS_)
#define _CORBA_STRING_256__ARG_TRAITS_

  struct CORBA_STRING_256 {};

  template<>
  class Arg_Traits<CORBA_STRING_256>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            256,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
  template<>
  struct  Array_Traits<
      Try::Foo::_values_forany
    >
  {
    static void free (
        Try::Foo::_values_slice * _tao_slice);
    static Try::Foo::_values_slice * dup (
        const Try::Foo::_values_slice * _tao_slice);
    static void copy (
        Try::Foo::_values_slice * _tao_to,
        const Try::Foo::_values_slice * _tao_from);
    static Try::Foo::_values_slice * alloc ();
    static void zero (
        Try::Foo::_values_slice * _tao_slice);
  };
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_enum/cdr_op_ch.cpp:33


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, Try::Color _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, Try::Color &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Try::Foo &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Try::Foo &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_array/cdr_op_ch.cpp:98


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 CORBA::Boolean operator<< (TAO_OutputCDR &strm, const Try::Foo::_values_forany &_tao_array);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Try::Foo::_values_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_Try_Foo__tao_seq_CORBA_Long__H_
#define _TAO_CDR_OP_Try_Foo__tao_seq_CORBA_Long__H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Try::Foo::_tao_seq_CORBA_Long_ &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Try::Foo::_tao_seq_CORBA_Long_ &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_Try_Foo__tao_seq_CORBA_Long__H_ */
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1648

#endif /* ifndef */

