// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "FooTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Try::FooTypeSupport.

Try::FooTypeSupport_ptr
TAO::Objref_Traits<Try::FooTypeSupport>::duplicate (Try::FooTypeSupport_ptr p)
{
  return Try::FooTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Try::FooTypeSupport>::release (Try::FooTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Try::FooTypeSupport_ptr
TAO::Objref_Traits<Try::FooTypeSupport>::nil ()
{
  return Try::FooTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Try::FooTypeSupport>::marshal (const Try::FooTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Try::FooTypeSupport::FooTypeSupport ()
{}Try::FooTypeSupport_ptr
Try::FooTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return FooTypeSupport::_duplicate (
      dynamic_cast<FooTypeSupport_ptr> (_tao_objref));
}

Try::FooTypeSupport_ptr
Try::FooTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return FooTypeSupport::_duplicate (
      dynamic_cast<FooTypeSupport_ptr> (_tao_objref));
}

Try::FooTypeSupport_ptr
Try::FooTypeSupport::_nil ()
{
  return nullptr;
}

Try::FooTypeSupport_ptr
Try::FooTypeSupport::_duplicate (FooTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Try::FooTypeSupport::_tao_release (FooTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Try::FooTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:Try/FooTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Try::FooTypeSupport::_interface_repository_id () const
{
  return "IDL:Try/FooTypeSupport:1.0";
}

::CORBA::Boolean
Try::FooTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Try::FooDataWriter.

Try::FooDataWriter_ptr
TAO::Objref_Traits<Try::FooDataWriter>::duplicate (Try::FooDataWriter_ptr p)
{
  return Try::FooDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Try::FooDataWriter>::release (Try::FooDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Try::FooDataWriter_ptr
TAO::Objref_Traits<Try::FooDataWriter>::nil ()
{
  return Try::FooDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Try::FooDataWriter>::marshal (const Try::FooDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Try::FooDataWriter::FooDataWriter ()
{}Try::FooDataWriter_ptr
Try::FooDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return FooDataWriter::_duplicate (
      dynamic_cast<FooDataWriter_ptr> (_tao_objref));
}

Try::FooDataWriter_ptr
Try::FooDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return FooDataWriter::_duplicate (
      dynamic_cast<FooDataWriter_ptr> (_tao_objref));
}

Try::FooDataWriter_ptr
Try::FooDataWriter::_nil ()
{
  return nullptr;
}

Try::FooDataWriter_ptr
Try::FooDataWriter::_duplicate (FooDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Try::FooDataWriter::_tao_release (FooDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Try::FooDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:Try/FooDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Try::FooDataWriter::_interface_repository_id () const
{
  return "IDL:Try/FooDataWriter:1.0";
}

::CORBA::Boolean
Try::FooDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Try::FooDataReader.

Try::FooDataReader_ptr
TAO::Objref_Traits<Try::FooDataReader>::duplicate (Try::FooDataReader_ptr p)
{
  return Try::FooDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Try::FooDataReader>::release (Try::FooDataReader_ptr p)
{
  ::CORBA::release (p);
}

Try::FooDataReader_ptr
TAO::Objref_Traits<Try::FooDataReader>::nil ()
{
  return Try::FooDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Try::FooDataReader>::marshal (const Try::FooDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Try::FooDataReader::FooDataReader ()
{}Try::FooDataReader_ptr
Try::FooDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return FooDataReader::_duplicate (
      dynamic_cast<FooDataReader_ptr> (_tao_objref));
}

Try::FooDataReader_ptr
Try::FooDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return FooDataReader::_duplicate (
      dynamic_cast<FooDataReader_ptr> (_tao_objref));
}

Try::FooDataReader_ptr
Try::FooDataReader::_nil ()
{
  return nullptr;
}

Try::FooDataReader_ptr
Try::FooDataReader::_duplicate (FooDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Try::FooDataReader::_tao_release (FooDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Try::FooDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:Try/FooDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Try::FooDataReader::_interface_repository_id () const
{
  return "IDL:Try/FooDataReader:1.0";
}

::CORBA::Boolean
Try::FooDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

