// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_SRC_FOOTYPESUPPORTC_CWXZUO_H_
#define _TAO_IDL_SRC_FOOTYPESUPPORTC_CWXZUO_H_


#include /**/ <ace/config-all.h>

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include <tao/ORB.h>
#include <tao/SystemException.h>
#include <tao/Basic_Types_IDLv4.h>
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include <tao/ORB_Constants.h>
#include <dds/DCPS/ZeroCopyInfoSeq_T.h>
#include <dds/DCPS/ZeroCopySeq_T.h>
#include <tao/Object.h>
#include <tao/String_Manager_T.h>
#include <tao/Sequence_T.h>
#include <tao/Objref_VarOut_T.h>
#include <tao/Seq_Var_T.h>
#include <tao/Seq_Out_T.h>
#include <tao/Arg_Traits_T.h>
#include <tao/Basic_Arguments.h>
#include <tao/Special_Basic_Arguments.h>
#include <tao/Any_Insert_Policy_T.h>
#include <tao/Fixed_Size_Argument_T.h>
#include <tao/Var_Size_Argument_T.h>
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "FooC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"
#include "dds/DdsDynamicDataC.h"

#if TAO_MAJOR_VERSION != 4 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace Try
{

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Try::Foo, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> FooSeq;
  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_TRY_FOOTYPESUPPORT__VAR_OUT_CH_)
#define _TRY_FOOTYPESUPPORT__VAR_OUT_CH_

  class FooTypeSupport;
  using FooTypeSupport_ptr = FooTypeSupport*;
  using FooTypeSupport_var = TAO_Objref_Var_T<FooTypeSupport>;
  using FooTypeSupport_out = TAO_Objref_Out_T<FooTypeSupport>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  FooTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = FooTypeSupport_ptr;
    using _var_type = FooTypeSupport_var;
    using _out_type = FooTypeSupport_out;

    // The static operations.
    static FooTypeSupport_ptr _duplicate (FooTypeSupport_ptr obj);

    static void _tao_release (FooTypeSupport_ptr obj);

    static FooTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static FooTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static FooTypeSupport_ptr _nil ();

    virtual ::DDS::ReturnCode_t create_sample_rc (
      ::Try::Foo & dst,
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::Try::Foo * create_sample (
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDS::ReturnCode_t create_dynamic_sample_rc (
      ::DDS::DynamicData_ptr & dst,
      const ::Try::Foo & src) = 0;

    virtual ::DDS::DynamicData_ptr create_dynamic_sample (
      const ::Try::Foo & src) = 0;

    virtual ::DDS::ReturnCode_t encode_to_string (
      const ::Try::Foo & sample,
      ::CORBA::String_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t encode_to_bytes (
      const ::Try::Foo & sample,
      ::DDS::OctetSeq_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_string (
      const char * encoded,
      ::Try::Foo_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_bytes (
      const ::DDS::OctetSeq & encoded,
      ::Try::Foo_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    FooTypeSupport ();

    

    virtual ~FooTypeSupport () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    FooTypeSupport (const FooTypeSupport &) = delete;
    FooTypeSupport (FooTypeSupport &&) = delete;
    FooTypeSupport &operator= (const FooTypeSupport &) = delete;
    FooTypeSupport &operator= (FooTypeSupport &&) = delete;
  };
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_TRY_FOODATAWRITER__VAR_OUT_CH_)
#define _TRY_FOODATAWRITER__VAR_OUT_CH_

  class FooDataWriter;
  using FooDataWriter_ptr = FooDataWriter*;
  using FooDataWriter_var = TAO_Objref_Var_T<FooDataWriter>;
  using FooDataWriter_out = TAO_Objref_Out_T<FooDataWriter>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  FooDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = FooDataWriter_ptr;
    using _var_type = FooDataWriter_var;
    using _out_type = FooDataWriter_out;

    // The static operations.
    static FooDataWriter_ptr _duplicate (FooDataWriter_ptr obj);

    static void _tao_release (FooDataWriter_ptr obj);

    static FooDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static FooDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static FooDataWriter_ptr _nil ();

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Try::Foo & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Try::Foo & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Try::Foo & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Try::Foo & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Try::Foo & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Try::Foo & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Try::Foo & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Try::Foo & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Try::Foo & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Try::Foo & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    FooDataWriter ();

    

    virtual ~FooDataWriter () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    FooDataWriter (const FooDataWriter &) = delete;
    FooDataWriter (FooDataWriter &&) = delete;
    FooDataWriter &operator= (const FooDataWriter &) = delete;
    FooDataWriter &operator= (FooDataWriter &&) = delete;
  };
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_TRY_FOODATAREADER__VAR_OUT_CH_)
#define _TRY_FOODATAREADER__VAR_OUT_CH_

  class FooDataReader;
  using FooDataReader_ptr = FooDataReader*;
  using FooDataReader_var = TAO_Objref_Var_T<FooDataReader>;
  using FooDataReader_out = TAO_Objref_Out_T<FooDataReader>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  FooDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:297

    using _ptr_type = FooDataReader_ptr;
    using _var_type = FooDataReader_var;
    using _out_type = FooDataReader_out;

    // The static operations.
    static FooDataReader_ptr _duplicate (FooDataReader_ptr obj);

    static void _tao_release (FooDataReader_ptr obj);

    static FooDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static FooDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static FooDataReader_ptr _nil ();

    virtual ::DDS::ReturnCode_t read (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Try::FooSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Try::FooSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Try::Foo & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Try::Foo & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Try::FooSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Try::FooSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Try::FooSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Try::Foo & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Try::Foo & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    FooDataReader ();

    

    virtual ~FooDataReader () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    FooDataReader (const FooDataReader &) = delete;
    FooDataReader (FooDataReader &&) = delete;
    FooDataReader &operator= (const FooDataReader &) = delete;
    FooDataReader &operator= (FooDataReader &&) = delete;
  };


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module Try
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_TRY_FOOTYPESUPPORT__TRAITS_)
#define _TRY_FOOTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Try::FooTypeSupport>
  {
    static ::Try::FooTypeSupport_ptr duplicate (::Try::FooTypeSupport_ptr p);
    static void release (::Try::FooTypeSupport_ptr p);
    static ::Try::FooTypeSupport_ptr nil ();
    static ::CORBA::Boolean marshal (const ::Try::FooTypeSupport_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_TRY_FOODATAWRITER__TRAITS_)
#define _TRY_FOODATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Try::FooDataWriter>
  {
    static ::Try::FooDataWriter_ptr duplicate (::Try::FooDataWriter_ptr p);
    static void release (::Try::FooDataWriter_ptr p);
    static ::Try::FooDataWriter_ptr nil ();
    static ::CORBA::Boolean marshal (const ::Try::FooDataWriter_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_TRY_FOODATAREADER__TRAITS_)
#define _TRY_FOODATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Try::FooDataReader>
  {
    static ::Try::FooDataReader_ptr duplicate (::Try::FooDataReader_ptr p);
    static void release (::Try::FooDataReader_ptr p);
    static ::Try::FooDataReader_ptr nil ();
    static ::CORBA::Boolean marshal (const ::Try::FooDataReader_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1648

#endif /* ifndef */

