/* Generated by opendds_idl version 3.29.1 (ACE version 8.0.0) running on input file idl/Foo.idl */
#include "FooTypeSupportImpl.h"

#include <cstring>
#include <stdexcept>
#ifndef OPENDDS_SAFETY_PROFILE
  #include "dds/CorbaSeq/LongSeqTypeSupportImpl.h"
#endif
#include "dds/DCPS/BuiltInTopicUtils.h"
#include "dds/DCPS/ContentFilteredTopicImpl.h"
#include "dds/DCPS/DataReaderImpl_T.h"
#include "dds/DCPS/DataWriterImpl_T.h"
#include "dds/DCPS/FilterEvaluator.h"
#include "dds/DCPS/MultiTopicDataReader_T.h"
#include "dds/DCPS/PoolAllocator.h"
#include "dds/DCPS/PublicationInstance.h"
#include "dds/DCPS/PublisherImpl.h"
#include "dds/DCPS/Qos_Helper.h"
#include "dds/DCPS/RakeData.h"
#include "dds/DCPS/RakeResults_T.h"
#include "dds/DCPS/ReceivedDataElementList.h"
#include "dds/DCPS/Registered_Data_Types.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/SubscriberImpl.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueCommon.h"
#include "dds/DCPS/XTypes/TypeObject.h"
#include "dds/DCPS/debug.h"
#include "dds/DdsDcpsDomainC.h"
#include "dds/DCPS/JsonValueReader.h"
#include "dds/DCPS/JsonValueWriter.h"

#ifdef OPENDDS_IDL_FILE_SPECIFIC
#  undef OPENDDS_IDL_FILE_SPECIFIC
#endif
#define OPENDDS_IDL_FILE_SPECIFIC(base, index) opendds_idl_generated_footypesupportimpl_cpp_3ctdfh##_##base##index



/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Try */



/* Begin ENUM: Color */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

const ListEnumHelper::Pair gen_Try_Color_pairs[] = {
  {"RED", static_cast<ACE_CDR::Long>( ::Try::RED)},
  {"GREEN", static_cast<ACE_CDR::Long>( ::Try::GREEN)},
  {"BLUE", static_cast<ACE_CDR::Long>( ::Try::BLUE)},
  {0, 0}};
const ListEnumHelper gen_Try_Color_helper_impl(gen_Try_Color_pairs);
const EnumHelper* gen_Try_Color_helper = &gen_Try_Color_helper_impl;

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Try_Color_xtag>()
{
  static XTypes::TypeIdentifier ti;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), ti);
  if (ti.kind() == XTypes::TK_NONE) {
    ti = XTypes::TypeIdentifier(XTypes::EK_MINIMAL, XTypes::EquivalenceHashWrapper(226, 140, 174, 253, 96, 228, 179, 20, 234, 251, 116, 7, 128, 35));
  }
  return ti;
}

static const XTypes::TypeMap& OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map, 0)();
static const XTypes::TypeMap& OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map, 0)();
template<> const XTypes::TypeMap& getMinimalTypeMap<Try_Color_xtag>()
{
  return OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map, 0)();
}

template<> const XTypes::TypeIdentifier& getCompleteTypeIdentifier<Try_Color_xtag>()
{
  static XTypes::TypeIdentifier ti;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), ti);
  if (ti.kind() == XTypes::TK_NONE) {
    ti = XTypes::TypeIdentifier(XTypes::EK_COMPLETE, XTypes::EquivalenceHashWrapper(220, 220, 252, 159, 143, 146, 97, 11, 96, 237, 103, 64, 180, 170));
  }
  return ti;
}

template<> const XTypes::TypeMap& getCompleteTypeMap<Try_Color_xtag>()
{
  return OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map, 0)();
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Try::Color& value)
{
  ACE_UNUSED_ARG(value_reader);
  ACE_UNUSED_ARG(value);
  return value_reader.read_enum(value, * ::OpenDDS::DCPS::gen_Try_Color_helper);
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Try::Color& value)
{
  ACE_UNUSED_ARG(value_writer);
  ACE_UNUSED_ARG(value);
  return value_writer.write_enum(value, * ::OpenDDS::DCPS::gen_Try_Color_helper);
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool operator<<(Serializer& strm, const  ::Try::Color& enumval)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(enumval);
  return strm << static_cast<ACE_CDR::Long>(enumval);
}

bool operator>>(Serializer& strm,  ::Try::Color& enumval)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(enumval);
  ACE_CDR::Long temp = 0;
  if (strm >> temp) {
    if (! ::OpenDDS::DCPS::gen_Try_Color_helper->valid(temp)) {
      strm.set_construction_status(Serializer::ElementConstructionFailure);
      return false;
    }
    enumval = static_cast< ::Try::Color>(temp);
    return true;
  }
  return false;
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End ENUM: Color */


/* Begin STRUCT: Foo */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Try_Foo_xtag>()
{
  static XTypes::TypeIdentifier ti;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), ti);
  if (ti.kind() == XTypes::TK_NONE) {
    ti = XTypes::TypeIdentifier(XTypes::EK_MINIMAL, XTypes::EquivalenceHashWrapper(66, 37, 112, 89, 39, 164, 25, 227, 16, 132, 142, 7, 0, 148));
  }
  return ti;
}

template<> const XTypes::TypeMap& getMinimalTypeMap<Try_Foo_xtag>()
{
  return OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map, 0)();
}

template<> const XTypes::TypeIdentifier& getCompleteTypeIdentifier<Try_Foo_xtag>()
{
  static XTypes::TypeIdentifier ti;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), ti);
  if (ti.kind() == XTypes::TK_NONE) {
    ti = XTypes::TypeIdentifier(XTypes::EK_COMPLETE, XTypes::EquivalenceHashWrapper(33, 15, 217, 81, 129, 5, 213, 235, 149, 13, 242, 164, 141, 145));
  }
  return ti;
}

template<> const XTypes::TypeMap& getCompleteTypeMap<Try_Foo_xtag>()
{
  return OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map, 0)();
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Try::Foo& value)
{
  ACE_UNUSED_ARG(value_reader);
  ACE_UNUSED_ARG(value);
  static const ListMemberHelper::Pair pairs[] = {{"bazz",0},{"temp",1},{"values",2},{"dynamic",3},{"fav",4},{0,0}};
  ListMemberHelper helper(pairs);
  if (!value_reader.begin_struct(OpenDDS::DCPS::APPENDABLE)) return false;
  XTypes::MemberId member_id;
  while (value_reader.members_remaining()) {
    if (!value_reader.begin_struct_member(member_id, helper)) return false;
    switch (member_id) {
    case 0: {
      {
        String x;
        if (!value_reader.read_string(x)) return false;
        value.bazz = x.c_str();
      }
      break;
    }
    case 1: {
      if (!value_reader.read_float64(value.temp)) return false;
      break;
    }
    case 2: {
      if (!value_reader.begin_array(XTypes::TK_INT32)) return false;
      if (!value_reader.read_int32_array (value.values, 5)) return false;
      if (!value_reader.end_array()) return false;
      break;
    }
    case 3: {
      if (!value_reader.begin_sequence(XTypes::TK_INT32)) return false;
      for (unsigned int i = 0; value_reader.elements_remaining(); ++i) {
       OpenDDS::DCPS::grow(value.dynamic);
        if (!value_reader.begin_element()) return false;
        if (!value_reader.read_int32(value.dynamic[i])) return false;
        if (!value_reader.end_element()) return false;
      }
      if (!value_reader.end_sequence()) return false;
      break;
    }
    case 4: {
      if (!vread(value_reader, value.fav)) return false;
      break;
    }
    }
    if (!value_reader.end_struct_member()) return false;
  }
  if (!value_reader.end_struct()) return false;
  return true;
}

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::Try::Foo>& value)
{
  ACE_UNUSED_ARG(value_reader);
  ACE_UNUSED_ARG(value);
  static const ListMemberHelper::Pair pairs[] = {{"bazz",0},{"temp",1},{"values",2},{"dynamic",3},{"fav",4},{0,0}};
  ListMemberHelper helper(pairs);
  if (!value_reader.begin_struct(OpenDDS::DCPS::APPENDABLE)) return false;
  XTypes::MemberId member_id;
  while (value_reader.members_remaining()) {
    if (!value_reader.begin_struct_member(member_id, helper)) return false;
    switch (member_id) {
    case 0: {
      {
        String x;
        if (!value_reader.read_string(x)) return false;
        value.value.bazz = x.c_str();
      }
      break;
    }
    case 1: {
      if (!value_reader.read_float64(value.value.temp)) return false;
      break;
    }
    case 2: {
      if (!value_reader.begin_array(XTypes::TK_INT32)) return false;
      if (!value_reader.read_int32_array (value.value.values, 5)) return false;
      if (!value_reader.end_array()) return false;
      break;
    }
    case 3: {
      if (!value_reader.begin_sequence(XTypes::TK_INT32)) return false;
      for (unsigned int i = 0; value_reader.elements_remaining(); ++i) {
       OpenDDS::DCPS::grow(value.value.dynamic);
        if (!value_reader.begin_element()) return false;
        if (!value_reader.read_int32(value.value.dynamic[i])) return false;
        if (!value_reader.end_element()) return false;
      }
      if (!value_reader.end_sequence()) return false;
      break;
    }
    case 4: {
      if (!vread(value_reader, value.value.fav)) return false;
      break;
    }
    }
    if (!value_reader.end_struct_member()) return false;
  }
  if (!value_reader.end_struct()) return false;
  return true;
}

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const KeyOnly< ::Try::Foo>& value)
{
  ACE_UNUSED_ARG(value_reader);
  ACE_UNUSED_ARG(value);
  static const ListMemberHelper::Pair pairs[] = {{0,0}};
  ListMemberHelper helper(pairs);
  if (!value_reader.begin_struct(OpenDDS::DCPS::APPENDABLE)) return false;
  if (!value_reader.end_struct()) return false;
  return true;
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Try::Foo& value)
{
  ACE_UNUSED_ARG(value_writer);
  ACE_UNUSED_ARG(value);
  if (!value_writer.begin_struct(OpenDDS::DCPS::APPENDABLE)) {
    return false;
  }
  {
    MemberParam param(0, false, "bazz", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_string(value.bazz)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(1, false, "temp", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.temp)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(2, false, "values", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.begin_array(XTypes::TK_INT32)) {
        return false;
      }
      if (!value_writer.write_int32_array (value.values, 5)) {
        return false;
      }
      if (!value_writer.end_array()) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(3, false, "dynamic", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.begin_sequence(XTypes::TK_INT32, static_cast<ACE_CDR::ULong>(value.dynamic.length()))) {
        return false;
      }
      if (!value_writer.write_int32_array (value.dynamic.get_buffer(), static_cast<ACE_CDR::ULong>(value.dynamic.length()))) {
        return false;
      }
      if (!value_writer.end_sequence()) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(4, false, "fav", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!vwrite(value_writer, value.fav)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  return value_writer.end_struct();
}

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::Try::Foo>& value)
{
  ACE_UNUSED_ARG(value_writer);
  ACE_UNUSED_ARG(value);
  if (!value_writer.begin_struct(OpenDDS::DCPS::APPENDABLE)) {
    return false;
  }
  {
    MemberParam param(0, false, "bazz", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_string(value.value.bazz)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(1, false, "temp", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.value.temp)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(2, false, "values", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.begin_array(XTypes::TK_INT32)) {
        return false;
      }
      if (!value_writer.write_int32_array (value.value.values, 5)) {
        return false;
      }
      if (!value_writer.end_array()) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(3, false, "dynamic", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.begin_sequence(XTypes::TK_INT32, static_cast<ACE_CDR::ULong>(value.value.dynamic.length()))) {
        return false;
      }
      if (!value_writer.write_int32_array (value.value.dynamic.get_buffer(), static_cast<ACE_CDR::ULong>(value.value.dynamic.length()))) {
        return false;
      }
      if (!value_writer.end_sequence()) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(4, false, "fav", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!vwrite(value_writer, value.value.fav)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  return value_writer.end_struct();
}

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const KeyOnly<const  ::Try::Foo>& value)
{
  ACE_UNUSED_ARG(value_writer);
  ACE_UNUSED_ARG(value);
  if (!value_writer.begin_struct(OpenDDS::DCPS::APPENDABLE)) {
    return false;
  }
  return value_writer.end_struct();
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::Try::Foo& stru)
{
  ACE_UNUSED_ARG(stru);
  stru.bazz = "";
  stru.temp = 0;
   ::Try::Foo::_values_forany stru_values_temp(const_cast< ::Try::Foo::_values_slice*>(stru.values));
  set_default(stru_values_temp);
  stru.dynamic.length(0);
  stru.fav =  ::Try::RED;
}

template<> void set_default( ::Try::Foo::_values_forany& arr)
{
  ACE_UNUSED_ARG(arr);
  for (CORBA::ULong i0 = 0; i0 < 5; ++i0) {
    arr[i0] = 0;
  }
}

void serialized_size(const Encoding& encoding, size_t& size, const  ::Try::Foo::_values_forany& arr)
{
  ACE_UNUSED_ARG(encoding);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(arr);
  primitive_serialized_size(encoding, size,  ::CORBA::Long(), 5);
}

bool operator<<(Serializer& strm, const  ::Try::Foo::_values_forany& arr)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(arr);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  return strm.write_long_array(arr.in(), 5);
}

bool operator>>(Serializer& strm,  ::Try::Foo::_values_forany& arr)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(arr);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  return strm.read_long_array(arr.out(), 5);
}

void serialized_size(const Encoding& encoding, size_t& size, const  ::Try::Foo::_dynamic_seq& seq)
{
  ACE_UNUSED_ARG(encoding);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(seq);
  primitive_serialized_size_ulong(encoding, size);
  if (seq.length() == 0) {
    return;
  }
  primitive_serialized_size(encoding, size,  ::CORBA::Long(), seq.length());
}

bool operator<<(Serializer& strm, const  ::Try::Foo::_dynamic_seq& seq)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(seq);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  const CORBA::ULong length = seq.length();
  if (!(strm << length)) {
    return false;
  }
  if (length == 0) {
    return true;
  }
  return strm.write_long_array(seq.get_buffer(), length);
}

bool operator>>(Serializer& strm,  ::Try::Foo::_dynamic_seq& seq)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(seq);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  CORBA::ULong length;
  if (!(strm >> length)) {
    return false;
  }
  if (length > strm.length()) {
    if (DCPS_debug_level >= 8) {
      ACE_DEBUG((LM_DEBUG, ACE_TEXT("(%P|%t) Invalid sequence length (%u)\n"), length));
    }
    return false;
  }
  CORBA::ULong new_length = length;
  seq.length(new_length);
  if (length == 0) {
    return true;
  }
  return strm.read_long_array(seq.get_buffer(), length);
  return true;
}

void serialized_size(const Encoding& encoding, size_t& size, const ::Try::Foo& stru)
{
  ACE_UNUSED_ARG(encoding);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(stru);
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size_delimiter(encoding, size);
  }
   ::Try::Foo::_values_forany stru_values_forany(const_cast< ::Try::Foo::_values_slice*>(stru.values));
  primitive_serialized_size_ulong(encoding, size);
  size += ACE_OS::strlen(stru.bazz.in()) + 1;
  primitive_serialized_size(encoding, size, stru.temp);
  serialized_size(encoding, size, stru_values_forany);
  serialized_size(encoding, size, stru.dynamic);
  primitive_serialized_size_ulong(encoding, size);
}

bool operator<<(Serializer& strm, const ::Try::Foo& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size(encoding, total_size, stru);
    if (!strm.write_delimiter(total_size)) {
      return false;
    }
  }
   ::Try::Foo::_values_forany stru_values_forany(const_cast< ::Try::Foo::_values_slice*>(stru.values));
  return (strm << ACE_OutputCDR::from_string(stru.bazz.in(), 256))
    && (strm << stru.temp)
    && (strm << stru_values_forany)
    && (strm << stru.dynamic)
    && (strm << stru.fav);
}

bool operator>>(Serializer& strm,  ::Try::Foo& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  bool reached_end_of_struct = false;
  ACE_UNUSED_ARG(reached_end_of_struct);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    if (!strm.read_delimiter(total_size)) {
      return false;
    }
  }
  const size_t end_of_struct = strm.rpos() + total_size;

   ::Try::Foo::_values_forany stru_values_forany(const_cast< ::Try::Foo::_values_slice*>(stru.values));
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.bazz = "";
  } else {
    if (!(strm >> ACE_InputCDR::to_string(stru.bazz.out(), 256))) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.temp = 0;
  } else {
    if (!(strm >> stru.temp)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
     ::Try::Foo::_values_forany stru_values_temp(const_cast< ::Try::Foo::_values_slice*>(stru.values));
    set_default(stru_values_temp);
  } else {
    if (!(strm >> stru_values_forany)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.dynamic.length(0);
  } else {
    if (!(strm >> stru.dynamic)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.fav =  ::Try::RED;
  } else {
    if (!(strm >> stru.fav)) {
      return false;
    }
  }
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() < end_of_struct) {
    strm.skip(end_of_struct - strm.rpos());
  }
  return true;
}

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::Try::Foo>& stru)
{
  ACE_UNUSED_ARG(encoding);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(stru);
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size_delimiter(encoding, size);
  }
   ::Try::Foo::_values_forany stru_value_values_forany(const_cast< ::Try::Foo::_values_slice*>(stru.value.values));
  primitive_serialized_size_ulong(encoding, size);
  size += ACE_OS::strlen(stru.value.bazz.in()) + 1;
  primitive_serialized_size(encoding, size, stru.value.temp);
  serialized_size(encoding, size, stru_value_values_forany);
  serialized_size(encoding, size, stru.value.dynamic);
  primitive_serialized_size_ulong(encoding, size);
}

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::Try::Foo>& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size(encoding, total_size, stru);
    if (!strm.write_delimiter(total_size)) {
      return false;
    }
  }
   ::Try::Foo::_values_forany stru_value_values_forany(const_cast< ::Try::Foo::_values_slice*>(stru.value.values));
  return (strm << ACE_OutputCDR::from_string(stru.value.bazz.in(), 256))
    && (strm << stru.value.temp)
    && (strm << stru_value_values_forany)
    && (strm << stru.value.dynamic)
    && (strm << stru.value.fav);
}

bool operator>>(Serializer& strm, const NestedKeyOnly< ::Try::Foo>& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  bool reached_end_of_struct = false;
  ACE_UNUSED_ARG(reached_end_of_struct);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    if (!strm.read_delimiter(total_size)) {
      return false;
    }
  }
  const size_t end_of_struct = strm.rpos() + total_size;

   ::Try::Foo::_values_forany stru_value_values_forany(const_cast< ::Try::Foo::_values_slice*>(stru.value.values));
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.bazz = "";
  } else {
    if (!(strm >> ACE_InputCDR::to_string(stru.value.bazz.out(), 256))) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.temp = 0;
  } else {
    if (!(strm >> stru.value.temp)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
     ::Try::Foo::_values_forany stru_value_values_temp(const_cast< ::Try::Foo::_values_slice*>(stru.value.values));
    set_default(stru_value_values_temp);
  } else {
    if (!(strm >> stru_value_values_forany)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.dynamic.length(0);
  } else {
    if (!(strm >> stru.value.dynamic)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.fav =  ::Try::RED;
  } else {
    if (!(strm >> stru.value.fav)) {
      return false;
    }
  }
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() < end_of_struct) {
    strm.skip(end_of_struct - strm.rpos());
  }
  return true;
}

void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const ::Try::Foo>& stru)
{
  ACE_UNUSED_ARG(encoding);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(stru);
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size_delimiter(encoding, size);
  }
}

bool operator<<(Serializer& strm, const KeyOnly<const ::Try::Foo>& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size(encoding, total_size, stru);
    if (!strm.write_delimiter(total_size)) {
      return false;
    }
  }
  return true;
}

bool operator>>(Serializer& strm, const KeyOnly< ::Try::Foo>& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  bool reached_end_of_struct = false;
  ACE_UNUSED_ARG(reached_end_of_struct);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    if (!strm.read_delimiter(total_size)) {
      return false;
    }
  }
  const size_t end_of_struct = strm.rpos() + total_size;

  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() < end_of_struct) {
    strm.skip(end_of_struct - strm.rpos());
  }
  return true;
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
bool DDSTraits< ::Try::Foo>::is_key(const char* field)
{
  ACE_UNUSED_ARG(field);
  return false;
}
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace Try {
::DDS::DataWriter_ptr FooTypeSupportImpl::create_datawriter()
{
  typedef OpenDDS::DCPS::DataWriterImpl_T<Foo> DataWriterImplType;
  ::DDS::DataWriter_ptr writer_impl = ::DDS::DataWriter::_nil();
  ACE_NEW_NORETURN(writer_impl,
                   DataWriterImplType());
  return writer_impl;
}

::DDS::DataReader_ptr FooTypeSupportImpl::create_datareader()
{
  typedef OpenDDS::DCPS::DataReaderImpl_T<Foo> DataReaderImplType;
  ::DDS::DataReader_ptr reader_impl = ::DDS::DataReader::_nil();
  ACE_NEW_NORETURN(reader_impl,
                   DataReaderImplType());
  return reader_impl;
}

#ifndef OPENDDS_NO_MULTI_TOPIC
::DDS::DataReader_ptr FooTypeSupportImpl::create_multitopic_datareader()
{
  typedef OpenDDS::DCPS::DataReaderImpl_T<Foo> DataReaderImplType;
  typedef OpenDDS::DCPS::MultiTopicDataReader_T<Foo, DataReaderImplType> MultiTopicDataReaderImplType;
  ::DDS::DataReader_ptr multitopic_reader_impl = ::DDS::DataReader::_nil();
  ACE_NEW_NORETURN(multitopic_reader_impl,
                   MultiTopicDataReaderImplType());
  return multitopic_reader_impl;
}
#endif /* !OPENDDS_NO_MULTI_TOPIC */

#ifndef OPENDDS_SAFETY_PROFILE
Foo* FooTypeSupportImpl::create_sample(::DDS::DynamicData_ptr src)
{
  Foo* value = new Foo;
  const ::DDS::ReturnCode_t rc = OpenDDS::DCPS::TypeSupportImpl_T<Foo>::create_sample_rc(*value, src);
  if (rc != ::DDS::RETCODE_OK && OpenDDS::DCPS::log_level >= OpenDDS::DCPS::LogLevel::Warning) {
    ACE_ERROR((LM_WARNING, "(%P|%t) WARNING: FooTypeSupportImpl::create_sample: "
      "create_sample_rc failed: %C\n", OpenDDS::DCPS::retcode_to_string(rc)));
  }
  return value;
}
#endif

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
const OpenDDS::DCPS::MetaStruct& FooTypeSupportImpl::getMetaStructForType() const
{
  return OpenDDS::DCPS::getMetaStruct<Foo>();
}
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

namespace {
  OpenDDS::DCPS::TypeSupportInitializer<FooTypeSupportImpl> ts_init_Try_Foo;
}

const OpenDDS::XTypes::TypeIdentifier& FooTypeSupportImpl::getMinimalTypeIdentifier() const
{
  return OpenDDS::DCPS::getMinimalTypeIdentifier<OpenDDS::DCPS::Try_Foo_xtag>();
}

const OpenDDS::XTypes::TypeMap& FooTypeSupportImpl::getMinimalTypeMap() const
{
  return OpenDDS::DCPS::getMinimalTypeMap<OpenDDS::DCPS::Try_Foo_xtag>();
}

const OpenDDS::XTypes::TypeIdentifier& FooTypeSupportImpl::getCompleteTypeIdentifier() const
{
  return OpenDDS::DCPS::getCompleteTypeIdentifier<OpenDDS::DCPS::Try_Foo_xtag>();
}

const OpenDDS::XTypes::TypeMap& FooTypeSupportImpl::getCompleteTypeMap() const
{
  return OpenDDS::DCPS::getCompleteTypeMap<OpenDDS::DCPS::Try_Foo_xtag>();
}

::DDS::ReturnCode_t FooTypeSupportImpl::encode_to_string(const Foo& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format)
{
#if OPENDDS_HAS_JSON_VALUE_WRITER
  OpenDDS::DCPS::JsonRepresentationFormat_var jrf = OpenDDS::DCPS::JsonRepresentationFormat::_narrow(format);
  if (jrf) {
    rapidjson::StringBuffer buffer;
    rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
    OpenDDS::DCPS::JsonValueWriter<rapidjson::Writer<rapidjson::StringBuffer> > jvw(writer);
    if (!vwrite(jvw, in)) {
      return ::DDS::RETCODE_ERROR;
    }
    out = buffer.GetString();
    return ::DDS::RETCODE_OK;
  }
#else
  ACE_UNUSED_ARG(in);
  ACE_UNUSED_ARG(format);
#endif
  out = "";
  return ::DDS::RETCODE_UNSUPPORTED;
}

::DDS::ReturnCode_t FooTypeSupportImpl::encode_to_bytes(const Foo& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format)
{
#if OPENDDS_HAS_JSON_VALUE_WRITER
  OpenDDS::DCPS::JsonRepresentationFormat_var jrf = OpenDDS::DCPS::JsonRepresentationFormat::_narrow(format);
  if (jrf) {
    CORBA::String_var buffer;
    const ::DDS::ReturnCode_t ret = encode_to_string(in, buffer, format);
    if (ret == ::DDS::RETCODE_OK) {
      const ::DDS::UInt32 len = static_cast< ::DDS::UInt32>(std::strlen(buffer));
      out = new ::DDS::OctetSeq(len);
      out->length(len);
      std::memcpy(out->get_buffer(), buffer, len);
      return ::DDS::RETCODE_OK;
    } else {
      out = new ::DDS::OctetSeq();
      return ret;
    }
  }
#else
  ACE_UNUSED_ARG(in);
  ACE_UNUSED_ARG(format);
#endif
  out = new ::DDS::OctetSeq();
  return ::DDS::RETCODE_UNSUPPORTED;
}

::DDS::ReturnCode_t FooTypeSupportImpl::decode_from_string(const char* in, Foo_out out, OpenDDS::DCPS::RepresentationFormat* format)
{
  out = new Foo;
  OpenDDS::DCPS::set_default(*out);
#if OPENDDS_HAS_JSON_VALUE_READER
  OpenDDS::DCPS::JsonRepresentationFormat_var jrf = OpenDDS::DCPS::JsonRepresentationFormat::_narrow(format);
  if (jrf) {
    rapidjson::StringStream buffer(in);
    OpenDDS::DCPS::JsonValueReader<> jvr(buffer);
    return vread(jvr, *out) ? ::DDS::RETCODE_OK : ::DDS::RETCODE_ERROR;
  }
#else
  ACE_UNUSED_ARG(in);
  ACE_UNUSED_ARG(format);
#endif
  return ::DDS::RETCODE_UNSUPPORTED;
}

::DDS::ReturnCode_t FooTypeSupportImpl::decode_from_bytes(const ::DDS::OctetSeq& in, Foo_out out, OpenDDS::DCPS::RepresentationFormat* format)
{
#if OPENDDS_HAS_JSON_VALUE_READER
  OpenDDS::DCPS::JsonRepresentationFormat_var jrf = OpenDDS::DCPS::JsonRepresentationFormat::_narrow(format);
  if (jrf) {
    return decode_from_string(reinterpret_cast<const char*>(in.get_buffer()), out, format);
  }
#else
  ACE_UNUSED_ARG(in);
  ACE_UNUSED_ARG(format);
#endif
  out = new Foo();
  return ::DDS::RETCODE_UNSUPPORTED;
}

FooTypeSupport::_ptr_type FooTypeSupportImpl::_narrow(CORBA::Object_ptr obj)
{
  return TypeSupportType::_narrow(obj);
}
}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<>
struct MetaStructImpl< ::Try::Foo> : MetaStruct {
  typedef  ::Try::Foo T;

#ifndef OPENDDS_NO_MULTI_TOPIC
  void* allocate() const { return new T; }

  void deallocate(void* stru) const { delete static_cast<T*>(stru); }

  size_t numDcpsKeys() const { return 0; }

#endif /* OPENDDS_NO_MULTI_TOPIC */

  Value getValue(const void* stru, const char* field) const
  {
    const ::Try::Foo& typed = *static_cast<const ::Try::Foo*>(stru);
    ACE_UNUSED_ARG(typed);
    if (std::strcmp(field, "bazz") == 0) {
      return typed.bazz.in();
    }
    if (std::strcmp(field, "temp") == 0) {
      return typed.temp;
    }
    if (std::strcmp(field, "fav") == 0) {
      return gen_Try_Color_helper->get_name(typed.fav);
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Try::Foo)");
  }

  Value getValue(Serializer& strm, const char* field, TypeSupportImpl* = 0) const
  {
    const Encoding& encoding = strm.encoding();
    ACE_UNUSED_ARG(encoding);
    size_t total_size = 0;
    if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
      if (!strm.read_delimiter(total_size)) {
        throw std::runtime_error("Unable to reader delimiter in getValue");
      }
    }
    std::string base_field = field;
    const size_t index = base_field.find('.');
    std::string subfield;
    if (index != std::string::npos) {
      subfield = base_field.substr(index + 1);
      base_field = base_field.substr(0, index);
    }
    if (base_field == "bazz") {
      TAO::String_Manager val;
      if (!(strm >> val.out())) {
        throw std::runtime_error("Field 'bazz' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(strm >> len)) {
        throw std::runtime_error("String 'bazz' length could not be deserialized");
      }
      if (!strm.skip(len)) {
        throw std::runtime_error("String 'bazz' contents could not be skipped");
      }
    }
    if (base_field == "temp") {
      ACE_CDR::Double val;
      if (!(strm >> val)) {
        throw std::runtime_error("Field 'temp' could not be deserialized");
      }
      return val;
    } else {
      if (!strm.skip(1,  8 )) {
        throw std::runtime_error("Field 'temp' could not be skipped");
      }
    }
    if (!gen_skip_over(strm, static_cast< ::Try::Foo::_values_forany*>(0))) {
      throw std::runtime_error("Field " + OPENDDS_STRING(field) + " could not be skipped");
    }
    if (!gen_skip_over(strm, static_cast< ::Try::Foo::_dynamic_seq*>(0))) {
      throw std::runtime_error("Field " + OPENDDS_STRING(field) + " could not be skipped");
    }
    if (base_field == "fav") {
      ACE_CDR::Long val;
      if (!(strm >> val)) {
        throw std::runtime_error("Field 'fav' could not be deserialized");
      }
      if (!gen_Try_Color_helper->valid(val)) {
        throw std::runtime_error("Enum value invalid");
      }
      return gen_Try_Color_helper->get_name(val);
    } else {
      if (!strm.skip(1,  4 )) {
        throw std::runtime_error("Field 'fav' could not be skipped");
      }
    }
    if (!field[0]) {
      return 0;
    }
    throw std::runtime_error("Did not find field in getValue");
  }

  ComparatorBase::Ptr create_qc_comparator(const char* field, ComparatorBase::Ptr next) const
  {
    ACE_UNUSED_ARG(next);
    if (std::strcmp(field, "bazz") == 0) {
      return make_field_cmp(&T::bazz, next);
    }
    if (std::strcmp(field, "temp") == 0) {
      return make_field_cmp(&T::temp, next);
    }
    if (std::strcmp(field, "fav") == 0) {
      return make_field_cmp(&T::fav, next);
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Try::Foo)");
  }

#ifndef OPENDDS_NO_MULTI_TOPIC
  const char** getFieldNames() const
  {
    static const char* names[] = {"bazz", "temp", "values", "dynamic", "fav", 0};
    return names;
  }

  const void* getRawField(const void* stru, const char* field) const
  {
    if (std::strcmp(field, "bazz") == 0) {
      return &static_cast<const T*>(stru)->bazz;
    }
    if (std::strcmp(field, "temp") == 0) {
      return &static_cast<const T*>(stru)->temp;
    }
    if (std::strcmp(field, "values") == 0) {
      return &static_cast<const T*>(stru)->values;
    }
    if (std::strcmp(field, "dynamic") == 0) {
      return &static_cast<const T*>(stru)->dynamic;
    }
    if (std::strcmp(field, "fav") == 0) {
      return &static_cast<const T*>(stru)->fav;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Try::Foo)");
  }

  void assign(void* lhs, const char* field, const void* rhs,
    const char* rhsFieldSpec, const MetaStruct& rhsMeta) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    ACE_UNUSED_ARG(rhsFieldSpec);
    ACE_UNUSED_ARG(rhsMeta);
    if (std::strcmp(field, "bazz") == 0) {
      static_cast<T*>(lhs)->bazz = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "temp") == 0) {
      static_cast<T*>(lhs)->temp = *static_cast<const  ::CORBA::Double*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "values") == 0) {
       ::Try::Foo::_values* lhsArr = &static_cast<T*>(lhs)->values;
      const  ::Try::Foo::_values* rhsArr = static_cast<const  ::Try::Foo::_values*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      for (CORBA::ULong i0 = 0; i0 < 5; ++i0) {
        (*lhsArr)[i0] = (*rhsArr)[i0];
      }
      return;
    }
    if (std::strcmp(field, "dynamic") == 0) {
      static_cast<T*>(lhs)->dynamic = *static_cast<const  ::Try::Foo::_dynamic_seq*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "fav") == 0) {
      static_cast<T*>(lhs)->fav = *static_cast<const  ::Try::Color*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Try::Foo)");
  }

  bool compare(const void* lhs, const void* rhs, const char* field) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    if (std::strcmp(field, "bazz") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->bazz.in(), static_cast<const T*>(rhs)->bazz.in());
    }
    if (std::strcmp(field, "temp") == 0) {
      return static_cast<const T*>(lhs)->temp == static_cast<const T*>(rhs)->temp;
    }
    if (std::strcmp(field, "fav") == 0) {
      return static_cast<const T*>(lhs)->fav == static_cast<const T*>(rhs)->fav;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Try::Foo)");
  }
#endif /* OPENDDS_NO_MULTI_TOPIC */

};

template<>
const MetaStruct& getMetaStruct< ::Try::Foo>()
{
  static MetaStructImpl< ::Try::Foo> msi;
  return msi;
}

bool gen_skip_over(Serializer& ser,  ::Try::Foo::_values_forany*)
{
  ACE_UNUSED_ARG(ser);
  const Encoding& encoding = ser.encoding();
  ACE_UNUSED_ARG(encoding);
  return ser.skip(5, 4);
}

bool gen_skip_over(Serializer& ser,  ::Try::Foo::_dynamic_seq*)
{
  ACE_UNUSED_ARG(ser);
  const Encoding& encoding = ser.encoding();
  ACE_UNUSED_ARG(encoding);
  ACE_CDR::ULong length;
  if (!(ser >> length)) return false;
  return ser.skip(length, 4);
}

bool gen_skip_over(Serializer& ser,  ::Try::Foo*)
{
  ACE_UNUSED_ARG(ser);
  MetaStructImpl< ::Try::Foo>().getValue(ser, "");
  return true;
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
#if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
template <>
class DynamicDataAdapterImpl< ::Try::Foo::_values, Try_Foo__9values_dda_tag > : public DynamicDataAdapter_T< ::Try::Foo::_values> {
public:
  DynamicDataAdapterImpl(DDS::DynamicType_ptr type,  ::Try::Foo::_values& value)
    : DynamicDataAdapter_T< ::Try::Foo::_values>(type, value)
  {
  }

  DynamicDataAdapterImpl(DDS::DynamicType_ptr type, const  ::Try::Foo::_values& value)
    : DynamicDataAdapter_T< ::Try::Foo::_values>(type, value)
  {
  }

  DDS::ReturnCode_t clear_all_values()
  {
    const DDS::ReturnCode_t rc = assert_mutable("DynamicDataAdapter::clear_all_values");
    if (rc == DDS::RETCODE_OK) {
      OpenDDS::DCPS::set_default(value_);
    }
    return rc;
  }

  DDS::UInt32 get_item_count()
  {
    return 5;
  }

  bool serialized_size(const OpenDDS::DCPS::Encoding& enc, size_t& size, OpenDDS::DCPS::Sample::Extent ext) const
  {
    ACE_UNUSED_ARG(ext);
    OpenDDS::DCPS::serialized_size(enc, size,  ::Try::Foo::_values_forany(value_));
    return true;
  }

  bool serialize(OpenDDS::DCPS::Serializer& ser, OpenDDS::DCPS::Sample::Extent ext) const
  {
    ACE_UNUSED_ARG(ext);
    using namespace OpenDDS::DCPS;
    return ser <<  ::Try::Foo::_values_forany(value_);
  }

protected:
  DDS::ReturnCode_t get_raw_value(const char* method, void* dest, DDS::TypeKind tk, DDS::MemberId id)
  {
    const DDS::ReturnCode_t rc = check_index(method, id, 5);
    if (rc != DDS::RETCODE_OK) {
      return rc;
    }
    return get_simple_raw_value(method, dest, tk, (&value_[0])[id], id);
  }

  DDS::ReturnCode_t set_raw_value(const char* method, DDS::MemberId id, const void* source, DDS::TypeKind tk)
  {
    DDS::ReturnCode_t rc = assert_mutable(method);
    if (rc != DDS::RETCODE_OK) {
      return rc;
    }
    rc = check_index(method, id, 5);
    if (rc != DDS::RETCODE_OK) {
      return rc;
    }
    return set_simple_raw_value(method, (&value_[0])[id], id, source, tk);
  }
};

#endif // if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(DDS::DynamicType_ptr type, const  ::Try::Foo::_values& value)
{
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  if (type) {
    return new DynamicDataAdapterImpl< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(type, value);
  }
#  else
  ACE_UNUSED_ARG(type);
  ACE_UNUSED_ARG(value);
#  endif
  return 0;
}

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(DDS::DynamicType_ptr type,  ::Try::Foo::_values& value)
{
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  if (type) {
    return new DynamicDataAdapterImpl< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(type, value);
  }
#  else
  ACE_UNUSED_ARG(type);
  ACE_UNUSED_ARG(value);
#  endif
  return 0;
}

template <>
const  ::Try::Foo::_values* get_dynamic_data_adapter_value< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(DDS::DynamicData_ptr dd)
{
  ACE_UNUSED_ARG(dd);
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  typedef DynamicDataAdapterImpl< ::Try::Foo::_values, Try_Foo__9values_dda_tag> Dda;
  const Dda* const dda = dynamic_cast<Dda*>(dd);
  if (dda) {
    return &dda->wrapped();
  }
#  endif
  return 0;
}
#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
#if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
template <>
class DynamicDataAdapterImpl< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq > : public DynamicDataAdapter_T< ::Try::Foo::_dynamic_seq> {
public:
  DynamicDataAdapterImpl(DDS::DynamicType_ptr type,  ::Try::Foo::_dynamic_seq& value)
    : DynamicDataAdapter_T< ::Try::Foo::_dynamic_seq>(type, value)
  {
  }

  DynamicDataAdapterImpl(DDS::DynamicType_ptr type, const  ::Try::Foo::_dynamic_seq& value)
    : DynamicDataAdapter_T< ::Try::Foo::_dynamic_seq>(type, value)
  {
  }

  DDS::ReturnCode_t clear_all_values()
  {
    const DDS::ReturnCode_t rc = assert_mutable("DynamicDataAdapter::clear_all_values");
    if (rc == DDS::RETCODE_OK) {
      OpenDDS::DCPS::set_default(value_);
    }
    return rc;
  }

  DDS::UInt32 get_item_count()
  {
    return value_.length();
  }

  DDS::MemberId get_member_id_at_index_impl(DDS::UInt32 index)
  {
    const DDS::UInt32 count = value_.length();
    if (!read_only_ && index >= count) {
      value_.length(index + 1);
      return index;
    }
    return check_index("get_member_id_at_index", index, count) == DDS::RETCODE_OK ? index : MEMBER_ID_INVALID;
  }

  bool serialized_size(const OpenDDS::DCPS::Encoding& enc, size_t& size, OpenDDS::DCPS::Sample::Extent ext) const
  {
    ACE_UNUSED_ARG(ext);
    OpenDDS::DCPS::serialized_size(enc, size, value_);
    return true;
  }

  bool serialize(OpenDDS::DCPS::Serializer& ser, OpenDDS::DCPS::Sample::Extent ext) const
  {
    ACE_UNUSED_ARG(ext);
    using namespace OpenDDS::DCPS;
    return ser << value_;
  }

protected:
  DDS::ReturnCode_t get_raw_value(const char* method, void* dest, DDS::TypeKind tk, DDS::MemberId id)
  {
    const DDS::ReturnCode_t rc = check_index(method, id, value_.length());
    if (rc != DDS::RETCODE_OK) {
      return rc;
    }
    return get_simple_raw_value(method, dest, tk, value_[id], id);
  }

  DDS::ReturnCode_t set_raw_value(const char* method, DDS::MemberId id, const void* source, DDS::TypeKind tk)
  {
    DDS::ReturnCode_t rc = assert_mutable(method);
    if (rc != DDS::RETCODE_OK) {
      return rc;
    }
    rc = check_index(method, id, value_.length());
    if (rc != DDS::RETCODE_OK) {
      return rc;
    }
    return set_simple_raw_value(method, value_[id], id, source, tk);
  }
};

#endif // if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(DDS::DynamicType_ptr type, const  ::Try::Foo::_dynamic_seq& value)
{
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  if (type) {
    return new DynamicDataAdapterImpl< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(type, value);
  }
#  else
  ACE_UNUSED_ARG(type);
  ACE_UNUSED_ARG(value);
#  endif
  return 0;
}

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(DDS::DynamicType_ptr type,  ::Try::Foo::_dynamic_seq& value)
{
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  if (type) {
    return new DynamicDataAdapterImpl< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(type, value);
  }
#  else
  ACE_UNUSED_ARG(type);
  ACE_UNUSED_ARG(value);
#  endif
  return 0;
}

template <>
const  ::Try::Foo::_dynamic_seq* get_dynamic_data_adapter_value< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(DDS::DynamicData_ptr dd)
{
  ACE_UNUSED_ARG(dd);
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  typedef DynamicDataAdapterImpl< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq> Dda;
  const Dda* const dda = dynamic_cast<Dda*>(dd);
  if (dda) {
    return &dda->wrapped();
  }
#  endif
  return 0;
}
#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
#if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
template <>
class DynamicDataAdapterImpl< ::Try::Foo,  ::Try::Foo > : public DynamicDataAdapter_T< ::Try::Foo> {
public:
  DynamicDataAdapterImpl(DDS::DynamicType_ptr type,  ::Try::Foo& value)
    : DynamicDataAdapter_T< ::Try::Foo>(type, value)
  {
  }

  DynamicDataAdapterImpl(DDS::DynamicType_ptr type, const  ::Try::Foo& value)
    : DynamicDataAdapter_T< ::Try::Foo>(type, value)
  {
  }

  DDS::ReturnCode_t clear_all_values()
  {
    const DDS::ReturnCode_t rc = assert_mutable("DynamicDataAdapter::clear_all_values");
    if (rc == DDS::RETCODE_OK) {
      OpenDDS::DCPS::set_default(value_);
    }
    return rc;
  }

  DDS::UInt32 get_item_count()
  {
    return 5;
  }

  bool serialized_size(const OpenDDS::DCPS::Encoding& enc, size_t& size, OpenDDS::DCPS::Sample::Extent ext) const
  {
    using namespace OpenDDS::DCPS;
    if (ext == Sample::Full) {
      DCPS::serialized_size(enc, size, value_);
    } else if (ext == Sample::NestedKeyOnly) {
      const NestedKeyOnly<const  ::Try::Foo> nested_key_only(value_);
      DCPS::serialized_size(enc, size, nested_key_only);
    } else {
      KeyOnly<const  ::Try::Foo> key_only(value_);
      DCPS::serialized_size(enc, size, key_only);
    }
    return true;
  }

  bool serialize(OpenDDS::DCPS::Serializer& ser, OpenDDS::DCPS::Sample::Extent ext) const
  {
    using namespace OpenDDS::DCPS;
    if (ext == Sample::Full) {
      return ser << value_;
    } else if (ext == Sample::NestedKeyOnly) {
      NestedKeyOnly<const  ::Try::Foo> nested_key_only(value_);
      return ser << nested_key_only;
    } else {
      KeyOnly<const  ::Try::Foo> key_only(value_);
      return ser << key_only;
    }
  }

protected:
  DDS::ReturnCode_t get_raw_value(const char* method, void* dest, DDS::TypeKind tk, DDS::MemberId id)
  {
    switch (id) {
    case 0:
      {
        return get_s8_raw_value(method, dest, tk, value_.bazz, id);
      }
    case 1:
      {
        return get_simple_raw_value(method, dest, tk, value_.temp, id);
      }
    case 2:
      {
        return get_complex_raw_value< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(method, dest, tk, value_.values, id);
      }
    case 3:
      {
        return get_complex_raw_value< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(method, dest, tk, value_.dynamic, id);
      }
    case 4:
      {
        return get_enum_raw_value(method, dest, tk, value_.fav, id);
      }
    default:
      return invalid_id(method, id);
    }
  }

  DDS::ReturnCode_t set_raw_value(const char* method, DDS::MemberId id, const void* source, DDS::TypeKind tk)
  {
    DDS::ReturnCode_t rc = assert_mutable(method);
    if (rc != DDS::RETCODE_OK) {
      return rc;
    }
    switch (id) {
    case 0:
      {
        return set_s8_raw_value(method, value_.bazz.inout(), id, source, tk);
      }
    case 1:
      {
        return set_simple_raw_value(method, value_.temp, id, source, tk);
      }
    case 2:
      {
        return set_indirect_complex_raw_value< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(method, value_.values, id, source, tk);
      }
    case 3:
      {
        return set_direct_complex_raw_value< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(method, value_.dynamic, id, source, tk);
      }
    case 4:
      {
        return set_enum_raw_value(method, value_.fav, id, source, tk);
      }
    default:
      return invalid_id(method, id);
    }
  }
};

#endif // if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo,  ::Try::Foo>(DDS::DynamicType_ptr type, const  ::Try::Foo& value)
{
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  if (type) {
    return new DynamicDataAdapterImpl< ::Try::Foo,  ::Try::Foo>(type, value);
  }
#  else
  ACE_UNUSED_ARG(type);
  ACE_UNUSED_ARG(value);
#  endif
  return 0;
}

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo,  ::Try::Foo>(DDS::DynamicType_ptr type,  ::Try::Foo& value)
{
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  if (type) {
    return new DynamicDataAdapterImpl< ::Try::Foo,  ::Try::Foo>(type, value);
  }
#  else
  ACE_UNUSED_ARG(type);
  ACE_UNUSED_ARG(value);
#  endif
  return 0;
}

template <>
const  ::Try::Foo* get_dynamic_data_adapter_value< ::Try::Foo,  ::Try::Foo>(DDS::DynamicData_ptr dd)
{
  ACE_UNUSED_ARG(dd);
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  typedef DynamicDataAdapterImpl< ::Try::Foo,  ::Try::Foo> Dda;
  const Dda* const dda = dynamic_cast<Dda*>(dd);
  if (dda) {
    return &dda->wrapped();
  }
#  endif
  return 0;
}
#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: Foo */

/* End MODULE: Try */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

namespace {
XTypes::TypeObject OPENDDS_IDL_FILE_SPECIFIC(minimal_to, 0)()
{
  static const unsigned char to_bytes[] = { 133, 0, 0, 0, 241, 81, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 117, 0, 0, 0, 5, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 1, 0, 113, 0, 0, 1, 0, 0, 208, 110, 72, 26, 11, 0, 0, 0, 1, 0, 0, 0, 1, 0, 10, 61, 128, 26, 165, 0, 22, 0, 0, 0, 2, 0, 0, 0, 1, 0, 144, 243, 1, 0, 0, 0, 1, 0, 0, 0, 5, 4, 240, 156, 199, 238, 0, 0, 16, 0, 0, 0, 3, 0, 0, 0, 1, 0, 128, 243, 1, 0, 0, 4, 183, 47, 59, 211, 25, 0, 0, 0, 4, 0, 0, 0, 1, 0, 241, 226, 140, 174, 253, 96, 228, 179, 20, 234, 251, 116, 7, 128, 35, 235, 247, 230, 42  };
  XTypes::TypeObject to;
  if (!to_type_object(to_bytes, sizeof(to_bytes), to)) {
    throw std::runtime_error("Could not deserialize minimal Type Object 0");
  }
  return to;
}

XTypes::TypeObject OPENDDS_IDL_FILE_SPECIFIC(minimal_to, 1)()
{
  static const unsigned char to_bytes[] = { 78, 0, 0, 0, 241, 64, 2, 0, 2, 0, 0, 0, 32, 0, 0, 0, 62, 0, 0, 0, 3, 0, 0, 0, 14, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 64, 0, 162, 217, 84, 123, 0, 0, 14, 0, 0, 0, 6, 0, 0, 0, 1, 0, 0, 0, 0, 0, 157, 224, 229, 221, 0, 0, 14, 0, 0, 0, 6, 0, 0, 0, 2, 0, 0, 0, 0, 0, 27, 62, 30, 233  };
  XTypes::TypeObject to;
  if (!to_type_object(to_bytes, sizeof(to_bytes), to)) {
    throw std::runtime_error("Could not deserialize minimal Type Object 1");
  }
  return to;
}

XTypes::TypeMap OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map_private, 0)()
{
  XTypes::TypeMap tm;
  tm[XTypes::TypeIdentifier(XTypes::EK_MINIMAL, XTypes::EquivalenceHashWrapper(66, 37, 112, 89, 39, 164, 25, 227, 16, 132, 142, 7, 0, 148))] = OPENDDS_IDL_FILE_SPECIFIC(minimal_to, 0)();
  tm[XTypes::TypeIdentifier(XTypes::EK_MINIMAL, XTypes::EquivalenceHashWrapper(226, 140, 174, 253, 96, 228, 179, 20, 234, 251, 116, 7, 128, 35))] = OPENDDS_IDL_FILE_SPECIFIC(minimal_to, 1)();
  return tm;
}

XTypes::TypeObject OPENDDS_IDL_FILE_SPECIFIC(complete_to, 0)()
{
  const unsigned char to_bytes[] = {
198, 0, 0, 0, 242, 81, 2, 0, 17, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 84, 114, 121, 58, 58, 70, 111, 111, 0, 0, 0, 0, 166, 0, 0, 0, 5, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 1, 0, 113, 0, 0, 1, 0, 0, 5, 0, 0, 0, 98, 97, 122, 122, 0, 0, 0, 0, 19, 0, 0, 0, 1, 0, 0, 0, 1, 0, 10, 0, 5, 0, 0, 0, 116, 101, 109, 112, 0, 0, 0, 0, 33, 0, 0, 0, 2, 0, 0, 0, 1, 0, 144, 243, 1, 0, 0, 0, 1, 0, 0, 0, 5, 4, 0, 0, 7, 0, 0, 0, 118, 97, 108, 117, 101, 115, 0, 0, 0, 0, 0, 0, 26, 0, 0, 0, 3, 0, 0, 0, 1, 0, 128, 243, 1, 0, 0, 4, 8, 0, 0, 0, 100, 121, 110, 97, 109, 105, 99, 0, 0, 0, 0, 0, 34, 0, 0, 0, 4, 0, 0, 0, 1, 0, 242, 220, 220, 252, 159, 143, 146, 97, 11, 96, 237, 103, 64, 180, 170, 0, 0, 0, 4, 0, 0, 0, 102, 97, 118, 0, 0, 0  };
  XTypes::TypeObject to;
  if (!to_type_object(to_bytes, sizeof(to_bytes), to)) {
    throw std::runtime_error("Could not deserialize complete Type Object 0");
  }
  return to;
}

XTypes::TypeObject OPENDDS_IDL_FILE_SPECIFIC(complete_to, 1)()
{
  const unsigned char to_bytes[] = {
119, 0, 0, 0, 242, 64, 2, 0, 19, 0, 0, 0, 32, 0, 0, 0, 11, 0, 0, 0, 84, 114, 121, 58, 58, 67, 111, 108, 111, 114, 0, 0, 87, 0, 0, 0, 3, 0, 0, 0, 22, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 4, 0, 0, 0, 82, 69, 68, 0, 0, 0, 0, 0, 24, 0, 0, 0, 6, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 71, 82, 69, 69, 78, 0, 0, 0, 23, 0, 0, 0, 6, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 66, 76, 85, 69, 0, 0, 0  };
  XTypes::TypeObject to;
  if (!to_type_object(to_bytes, sizeof(to_bytes), to)) {
    throw std::runtime_error("Could not deserialize complete Type Object 1");
  }
  return to;
}

XTypes::TypeMap OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map_private, 0)()
{
  XTypes::TypeMap tm;
  tm[XTypes::TypeIdentifier(XTypes::EK_COMPLETE, XTypes::EquivalenceHashWrapper(33, 15, 217, 81, 129, 5, 213, 235, 149, 13, 242, 164, 141, 145))] = OPENDDS_IDL_FILE_SPECIFIC(complete_to, 0)();
  tm[XTypes::TypeIdentifier(XTypes::EK_COMPLETE, XTypes::EquivalenceHashWrapper(220, 220, 252, 159, 143, 146, 97, 11, 96, 237, 103, 64, 180, 170))] = OPENDDS_IDL_FILE_SPECIFIC(complete_to, 1)();
  return tm;
}
}

const XTypes::TypeMap& OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map, 0)()
{
  static XTypes::TypeMap tm;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), tm);
  if (tm.empty()) {
    tm = OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map_private, 0)();
  }
  return tm;
}

const XTypes::TypeMap& OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map, 0)()
{
  static XTypes::TypeMap tm;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), tm);
  if (tm.empty()) {
    tm = OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map_private, 0)();
  }
  return tm;
}
} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

