/* -*- C++ -*- */
/* Generated by opendds_idl version 3.29.1 (ACE version 8.0.0) running on input file idl/Foo.idl */
#ifndef OPENDDS_IDL_GENERATED_FOOTYPESUPPORTIMPL_H_3CTDFH
#define OPENDDS_IDL_GENERATED_FOOTYPESUPPORTIMPL_H_3CTDFH

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 29, 1)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "FooC.h"
#include "FooTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/TypeSupportImpl_T.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueDispatcher.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Try */



/* Begin ENUM: Color */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

extern const EnumHelper* gen_Try_Color_helper;
} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct Try_Color_xtag {};
template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Try_Color_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<Try_Color_xtag>();

template<> const XTypes::TypeIdentifier& getCompleteTypeIdentifier<Try_Color_xtag>();

template<> const XTypes::TypeMap& getCompleteTypeMap<Try_Color_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Try::Color& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Try::Color& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool operator<<(Serializer& strm, const  ::Try::Color& enumval);

bool operator>>(Serializer& strm,  ::Try::Color& enumval);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End ENUM: Color */


/* Begin STRUCT: Foo */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct Try_Foo_xtag {};
template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Try_Foo_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<Try_Foo_xtag>();

template<> const XTypes::TypeIdentifier& getCompleteTypeIdentifier<Try_Foo_xtag>();

template<> const XTypes::TypeMap& getCompleteTypeMap<Try_Foo_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Try::Foo& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::Try::Foo>& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const KeyOnly< ::Try::Foo>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Try::Foo& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::Try::Foo>& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const KeyOnly<const  ::Try::Foo>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::Try::Foo& stru);

template<> void set_default( ::Try::Foo::_values_forany& arr);

void serialized_size(const Encoding& encoding, size_t& size, const  ::Try::Foo::_values_forany& arr);

bool operator<<(Serializer& strm, const  ::Try::Foo::_values_forany& arr);

bool operator>>(Serializer& strm,  ::Try::Foo::_values_forany& arr);

void serialized_size(const Encoding& encoding, size_t& size, const  ::Try::Foo::_dynamic_seq& seq);

bool operator<<(Serializer& strm, const  ::Try::Foo::_dynamic_seq& seq);

bool operator>>(Serializer& strm,  ::Try::Foo::_dynamic_seq& seq);

void serialized_size(const Encoding& encoding, size_t& size, const ::Try::Foo& stru);

bool operator<<(Serializer& strm, const ::Try::Foo& stru);

bool operator>>(Serializer& strm,  ::Try::Foo& stru);

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::Try::Foo>& stru);

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::Try::Foo>& stru);

bool operator>>(Serializer& strm, const NestedKeyOnly< ::Try::Foo>& stru);

void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const ::Try::Foo>& stru);

bool operator<<(Serializer& strm, const KeyOnly<const ::Try::Foo>& stru);

bool operator>>(Serializer& strm, const KeyOnly< ::Try::Foo>& stru);

template <>
struct MarshalTraits< ::Try::Foo> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound();
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(0);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::Try::Foo&) { return false; }
  static bool from_message_block( ::Try::Foo&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Try {
/// This structure supports use of std::map with one or more keys.
struct  Foo_OpenDDS_KeyLessThan {
  bool operator()(const  ::Try::Foo&, const  ::Try::Foo&) const
  {
    // With no keys, return false to allow use of
    // map with just one entry
    return false;
  }
};
}

namespace Try {
class FooTypeSupportImpl;
}
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::Try::Foo> {
  typedef  ::Try::Foo MessageType;
  typedef  ::Try::FooSeq MessageSequenceType;
  typedef  ::Try::FooSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::Try::FooTypeSupport TypeSupportType;
  typedef  ::Try::FooTypeSupportImpl TypeSupportImplType;
  typedef  ::Try::FooDataWriter DataWriterType;
  typedef  ::Try::FooDataReader DataReaderType;
  typedef  ::Try::Foo_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::Try::Foo> KeyOnlyType;
  typedef OpenDDS::DCPS::Try_Foo_xtag XtagType;

  static const char* type_name() { return "Try::Foo"; }
  static size_t key_count() { return 0; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace Try {
class  FooTypeSupportImpl
  : public virtual OpenDDS::DCPS::TypeSupportImpl_T<Foo>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<Foo>
{
public:
  typedef FooTypeSupport TypeSupportType;
  typedef FooTypeSupport::_var_type _var_type;
  typedef FooTypeSupport::_ptr_type _ptr_type;

  FooTypeSupportImpl() {}
  virtual ~FooTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_SAFETY_PROFILE
  Foo* create_sample(::DDS::DynamicData_ptr src);
#endif
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  ::DDS::ReturnCode_t encode_to_string(const Foo& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t encode_to_bytes(const Foo& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_string(const char* in, Foo_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_bytes(const ::DDS::OctetSeq& in, Foo_out out, OpenDDS::DCPS::RepresentationFormat* format);

  static FooTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct< ::Try::Foo>();
bool gen_skip_over(Serializer& ser,  ::Try::Foo::_values_forany*);

bool gen_skip_over(Serializer& ser,  ::Try::Foo::_dynamic_seq*);

bool gen_skip_over(Serializer& ser,  ::Try::Foo*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
struct Try_Foo__9values_dda_tag {};

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(DDS::DynamicType_ptr type, const  ::Try::Foo::_values& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(DDS::DynamicType_ptr type,  ::Try::Foo::_values& value);

template <>
const  ::Try::Foo::_values* get_dynamic_data_adapter_value< ::Try::Foo::_values, Try_Foo__9values_dda_tag>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(DDS::DynamicType_ptr type, const  ::Try::Foo::_dynamic_seq& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(DDS::DynamicType_ptr type,  ::Try::Foo::_dynamic_seq& value);

template <>
const  ::Try::Foo::_dynamic_seq* get_dynamic_data_adapter_value< ::Try::Foo::_dynamic_seq,  ::Try::Foo::_dynamic_seq>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo,  ::Try::Foo>(DDS::DynamicType_ptr type, const  ::Try::Foo& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Try::Foo,  ::Try::Foo>(DDS::DynamicType_ptr type,  ::Try::Foo& value);

template <>
const  ::Try::Foo* get_dynamic_data_adapter_value< ::Try::Foo,  ::Try::Foo>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: Foo */

/* End MODULE: Try */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_FOOTYPESUPPORTIMPL_H_3CTDFH */
